baseURL = "https://example.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "CodeDrik"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = ""

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

[params]
description = """
CodeDrik
Observing Code
"""
copyright = "2021-{{ YEAR }}"
displayMode = "dark"
doNotLoadAnimations = true # Animations are loaded by default
singleDateFormat = "Mon, Jan 2, 2006"
indexDateFormat = "Mon, Jan 2, 2006"
listDateFormat = "Jan 2"
contentratio = 0.8
readMore = true




## Social links
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/gopikrishnan-bahuleyan/"

# use 'fab' when brand icons, use 'fas' when standard solid icons. https://fontawesome.com/
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/gopimails"

[[params.socialIcons]]
icon = "fab fa-youtube"
title = "YouTube"
url = "https://www.youtube.com/channel/UCFR2TnHAxxEGnIiP_0ARivQ"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/gopimails"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:gopi.mails@gmail.com"